spark_delta_project:
  target: delta
  outputs:
    delta:
      type: spark
      method: thrift
      schema: default
      host: localhost
      port: 10000
      thrift_transport: binary
      authentication: NOSASL
      file_format: delta
      connect_retries: 3
      connect_timeout: 3
      retry_all: true

spark_iceberg_project:
  target: delta
  outputs:
    delta:
      type: spark
      method: thrift
      schema: default
      host: localhost
      port: 10000
      thrift_transport: binary
      authentication: NOSASL
      file_format: iceberg
      connect_retries: 3
      connect_timeout: 3
      retry_all: true

spark_hive_project:
  target:
  outputs:
    hive:
      type: hive
      host: localhost
      port: 10000 # default value: 10000
      schema: default
