spark_dbt_project:
  target: delta_thrift
  outputs:
    delta_thrift:
      type: spark
      method: thrift
      host: localhost
      port: 10000
      schema: delta
      authentication: NOSASL
      connect_retries: 3
      connect_timeout: 10
      retry_all: true

    iceberg_thrift:
      type: spark
      method: thrift
      host: localhost
      port: 10001
      schema: iceberg
      authentication: NOSASL
      connect_retries: 3
      connect_timeout: 10
      retry_all: true
